# -*- coding: utf-8 -*-
"""Division_Train_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mr-pP0c3t0CsNQR4uUmviS_rDw_lV2vN
"""

# ==============================================================================
# División Estratégica: Train (2023) y Test (2024)
# ==============================================================================
# Aplico la técnica de entrenamiento temporal.
# Entrenare con los datos del 2023 (incluyendo la memoria de 2022)
# y validare con el año más reciente: 2024.
# ==============================================================================
import pandas as pd

# Defino el año de corte
ANIO_TEST = 2024

def realizar_split_temporal(df, nombre_archivo):
    """
    Divide el dataframe en Train (todo lo anterior a 2024) y Test (2024).
    Guarda los resultados automáticamente.
    """
    train = df[df['periodo'] < ANIO_TEST].copy()
    test = df[df['periodo'] == ANIO_TEST].copy()

    # Exportar
    train.to_csv(f'data/processed/train_{nombre_archivo}.csv', sep=';', index=False)
    test.to_csv(f'data/processed/test_{nombre_archivo}.csv', sep=';', index=False)

    return train, test