# -*- coding: utf-8 -*-
"""Feature Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAmE474V2yKtwRX5GjQ_DImJztW_kHbE
"""

# ==============================================================================
# Ingeniería de Características (Feature Engineering)
# ==============================================================================
# (Preparación para el Modelo)
# En esta sección transformare el dataset maestro Cibercriminalidad
# en dos flujos independientes:
# 1. Fraude (Alta densidad): requiere más historia (Lag 1, 2 y Media Móvil).
# 2. Otros (Baja densidad): requiere estructura simplificada (Lag 1).
# En esta fase se dotara de "memoria" al modelo.
# ==============================================================================
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin
# Definición de la clase transformadora
class FeatureEngineCibercrimen(BaseEstimator, TransformerMixin):
    """
    Transformador de Scikit-Learn que automatiza la creación de variables
    temporales. Permite tratar de forma distinta el Fraude y otros delitos.
    """
    def __init__(self, es_fraude=True):
        self.es_fraude = es_fraude

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        df = X.copy()
        # Ordenación cronológica por Provincia y Año:
        # Crucial para que los .shift() miren al pasado real
        df = df.sort_values(['Provincias', 'periodo'])

        if self.es_fraude:
            # ------------------------------------------------------------------
            # LÓGICA FRAUDE
            # ------------------------------------------------------------------
            #para que el cálculo se mantenga alineado con las filas originales
            grouped = df.groupby('Provincias')['Tasa_Criminalidad']

            # Crear Lags: T-1 (año anterior) y T-2 (dos años antes)
            df['Tasa_Lag_1'] = grouped.shift(1)
            df['Tasa_Lag_2'] = grouped.shift(2)

            # Media Móvil de 2 años: Suaviza la serie temporal para evitar ruido
            # y evita Data Leakage
            df['Media_Movil_2y'] = grouped.shift(1).rolling(window=2, min_periods=1).mean()


            # Imputación inteligente: Si Lag_2 no existe (ej. 2023), usa el Lag_1
            df['Tasa_Lag_2'] = df['Tasa_Lag_2'].fillna(df['Tasa_Lag_1'])


            # Limpieza: Elimino columnas redundantes o específicas de otros cibercrimen
            cols_to_drop = ['CCAA', 'codigo_ine', 'Total_Hechos', 'Peso_Tipologia']
            df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

        else:
            # ------------------------------------------------------------------
            # LÓGICA OTROS CIBERDELITOS: Granularidad por tipo de delito
            # (Baja Densidad / Ceros)
            # ------------------------------------------------------------------
            # Agrupo por Provincia y Tipo para mantener la especificidad
            # y no mezclar tipos de delitos
            grouped = df.groupby(['Provincias', 'Grupo penal'])['Tasa_Criminalidad']

            # Solo creo Lag_1 para evitar perder demasiados registros por falta de historial
            df['Tasa_Lag_1'] = grouped.shift(1)

            # Lag_2 se mantiene porque aporta estabilidad
            df['Tasa_Lag_2'] = grouped.shift(2)
            df['Tasa_Lag_2'] = df['Tasa_Lag_2'].fillna(df['Tasa_Lag_1'])

            # Calcular VAR_pct de forma segura
            # Uso una pequeña constante o fillna para evitar divisiones por cero
            df['VAR_pct'] = (df['Tasa_Criminalidad'] - df['Tasa_Lag_1']) / df['Tasa_Lag_1'].replace(0, np.nan)
            df['VAR_pct'] = df['VAR_pct'].fillna(0) # Si el año anterior era 0, la variación se trata como 0 o neutra


            # Limpieza: Elimino columnas específicas de Fraude que no aplican aquí
            # y columnas redundantes
            cols_to_drop = ['CCAA', 'codigo_ine', 'Total_Hechos', 'Peso_Fraude']
            df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

        # ----------------------------------------------------------------------
        # ELIMINACIÓN ESTRUCTURAL DE NULOS
        # ----------------------------------------------------------------------
        # ¿Por qué se hace dropna?
        # Al crear un Lag_1, el año 2022 se queda sin "año anterior" y genera un nulo.
        # Como el modelo no puede aprender sin su predictor principal, elimino esas filas.
        return df.dropna(subset=['Tasa_Lag_1'])