# -*- coding: utf-8 -*-
"""model_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AROeWqCpo1oERq11tXtohGO0EMhL9XDz
"""

# ==============================================================================
# Utilidades de Modelado: Métricas, Formateo y Pipeline de Preprocesamiento
# ==============================================================================

import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import RobustScaler, OneHotEncoder
from sklearn.pipeline import Pipeline

# ---------------------------------------------------------
# MÉTRICA WAPE
# ---------------------------------------------------------
def calcular_wape(y_true, y_pred):
    """
    Calcula el Error Porcentual Medio Ponderado (WAPE).
    Es la métrica más robusta cuando hay valores cercanos a cero.
    """
    return (np.sum(np.abs(y_true - y_pred)) / np.sum(y_true)) * 100


# ---------------------------------------------------------
# FORMATEO DE PARÁMETROS DEL GRIDSEARCH
# ---------------------------------------------------------
def formatear_params(params):
    """
    Limpia los parámetros del GridSearch eliminando el prefijo 'regressor__'
    para una visualización más clara.
    """
    params_limpios = {k.replace('regressor__', ''): v for k, v in params.items() if k != 'regressor'}
    return ", ".join([f"{k}={v}" for k, v in params_limpios.items()])


# ---------------------------------------------------------
# CREACIÓN DEL PIPELINE DE PREPROCESAMIENTO + MODELO
# ---------------------------------------------------------
def crear_pipeline(modelo, tipo_dataset):
    """
    Define el tratamiento de datos:
    - RobustScaler para manejar outliers (Madrid/BCN)
    - OneHotEncoder para variables categóricas
    - Modelo final (RandomForest, XGBoost, Ridge, etc.)
    """

    if tipo_dataset == "fraude":
        var_num = ['Poblacion_Provincial', 'Peso_Fraude', 'VAR_pct',
                   'Tasa_Lag_1', 'Tasa_Lag_2', 'Media_Movil_2y']
        var_cat = ['Provincias']

    else:
        var_num = ['Poblacion_Provincial', 'Peso_Tipologia', 'VAR_pct',
                   'Tasa_Lag_1', 'Tasa_Lag_2']
        var_cat = ['Provincias', 'Grupo penal']

    preprocessor = ColumnTransformer(
        transformers=[
            ('num', RobustScaler(), var_num),
            ('cat', OneHotEncoder(handle_unknown='ignore'), var_cat)
        ]
    )

    return Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('regressor', modelo)
    ])