# -*- coding: utf-8 -*-
"""pipeline_cibercrimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0NJsNM5gWB0zQe25lyH0tnjNNRWttug
"""

# ==============================================================================
#Código Pipeline unificado Cibercrimen (SEC + INE)
# Entrada: hechos_raw.csv + ine_raw.csv
# Salida: df_cibercrimen.csv (dataset maestro completo)
# ==============================================================================
import pandas as pd
import numpy as np
import re
import unicodedata
from sklearn.base import BaseEstimator, TransformerMixin
# ------------------------------------------------------------------------------
# Clase de Normalización de provinicas (Arquitectura reutilizable con sklearn)
# ------------------------------------------------------------------------------
class ProvinciaNormalizer(BaseEstimator, TransformerMixin):
    """
    OBJETIVO: Estandarizar nombres de provincias (ej: '01 Araba/Álava' -> 'araba')
    para que el cruce entre las tablas sea perfecto.
    """
    def fit(self, X, y=None):
        return self

    def _norm_string(self, text):
        if not isinstance(text, str): return ""
        text = re.sub(r"^\d{2}\s+", "", text)  # Quitar códigos INE
        text = "".join(c for c in unicodedata.normalize('NFD', text)
                       if unicodedata.category(c) != 'Mn')  # Quitar acentos
        text = re.split(r'[/|(|,]', text)[0].strip().lower()  # Limpiar barras/paréntesis
        return text.replace(" ", "_")

    def transform(self, X):
        df = X.copy()
        if "Provincias" in df.columns:
            df["Provincias"] = df["Provincias"].apply(self._norm_string)
        return df


# ------------------------------------------------------------------------------
# 2. CARGA Y ETL DE DATOS RAW (SEC + INE)
# ------------------------------------------------------------------------------
# OBJETIVO:
# A partir de los archivos originales descargados del SEC e INE:
#   - Cargar los datos en bruto (dtype=str para evitar problemas de tipos)
#   - Limpiar formatos numéricos
#   - Ajustar el desfase temporal del INE (población a 1 de enero → año anterior)
#   - Filtrar la ventana metodológica (2022–año máximo disponible)
#   - Devolver dos DataFrames limpios y sincronizados para el pipeline
# ------------------------------------------------------------------------------

def cargar_y_etl_raw(path_hechos, path_ine):

    # ---------------------------------------------------------
    # 1. CARGA DE ARCHIVOS RAW
    # ---------------------------------------------------------
    print("Iniciando carga de datos brutos SEC e INE")

    # Carga en bruto, manteniendo todo como texto para evitar errores de tipo
    df_h_raw = pd.read_csv(path_hechos, sep=';', dtype=str)
    df_p_raw = pd.read_csv(path_ine, sep=';', dtype=str)

    print("Archivos RAW cargados correctamente.\n")

    # ---------------------------------------------------------
    # 2. PROCESAMIENTO SEC – HECHOS
    # ---------------------------------------------------------
    # Copia de trabajo para no modificar el DataFrame original
    df_h = df_h_raw.copy()

    # Limpieza del formato numérico tradicional (eliminación de puntos de millar)
    df_h['Total'] = df_h['Total'].str.replace('.', '', regex=False).astype(int)

    # Conversión del periodo a entero
    df_h['periodo'] = df_h['periodo'].astype(int)

    # Criterio metodológico:
    # Se fija el inicio en 2022 por estabilidad estadística.
    ano_min = 2022
    ano_max = df_h['periodo'].max()  # Máximo dinámico según datos disponibles

    # Filtrado dinámico hacia el futuro respetando el inicio en 2022
    df_h = df_h[df_h['periodo'].between(ano_min, ano_max)].copy()

    # ---------------------------------------------------------
    # 3. PROCESAMIENTO INE – POBLACIÓN
    # ---------------------------------------------------------
    # Aislamiento de la población oficial residente:
    #   - Todas las edades
    #   - Sexo total
    #   - Datos referidos al 1 de enero (padrón continuo)
    df_p = df_p_raw[
        (df_p_raw['Generación'] == 'Todas las edades') &
        (df_p_raw['Sexo'] == 'Total') &
        (df_p_raw['Periodo'].str.contains('1 de enero', na=False))
    ].copy()

    # Eliminación de columnas no necesarias tras el filtrado
    df_p = df_p.drop(columns=['Generación', 'Sexo'])

    # Limpieza del formato numérico
    df_p['Total'] = df_p['Total'].str.replace('.', '', regex=False).astype(int)

    # Extracción del año y ajuste del desfase temporal:
    #   La población a 1 de enero de 2025 representa el cierre del periodo 2024.
    df_p['periodo'] = df_p['Periodo'].str.extract(r'(\d{4})').astype(int) - 1

    # Eliminación de la columna original de periodo textual
    df_p = df_p.drop(columns=['Periodo'])

    # Sincronización exacta con la ventana metodológica (2022–año máximo)
    df_p = df_p[df_p['periodo'].between(ano_min, ano_max)].copy()

    # ---------------------------------------------------------
    # 4. RETORNO DE LOS DATAFRAMES LIMPIOS
    # ---------------------------------------------------------
    return df_h, df_p



# ------------------------------------------------------------------------------
# 2. FUNCIÓN PRINCIPAL DEL PIPELINE (AJUSTADA A METODOLOGÍA 2022-2024)
# ------------------------------------------------------------------------------
def pipeline_limpieza_hechos(df_h, df_p):
    """
    Motor de unificación: a partir de los datasets limpios de Hechos (SEC)
    y Población (INE), realiza:
        - Filtrado básico de entidades no válidas
        - Normalización de nombres de provincias
        - Normalización de tipologías penales
        - Agregación de población por provincia y año
        - Unión SEC + INE
        - Asignación de CCAA
        - Cálculo de la tasa de criminalidad (x 1.000 habitantes)
    Devuelve un DataFrame maestro listo para el cálculo de métricas avanzadas.
    """

    # ----------------------------------------------------------------------
    # 1. MAPEO COMPLETO DE PROVINCIAS → CCAA
    # ----------------------------------------------------------------------
    mapeo_completo_ccaa = {
        'albacete': 'Castilla-La Mancha', 'ciudad_real': 'Castilla-La Mancha', 'cuenca': 'Castilla-La Mancha',
        'guadalajara': 'Castilla-La Mancha', 'toledo': 'Castilla-La Mancha',
        'avila': 'Castilla y León', 'burgos': 'Castilla y León', 'leon': 'Castilla y León',
        'palencia': 'Castilla y León', 'salamanca': 'Castilla y León', 'segovia': 'Castilla y León',
        'soria': 'Castilla y León', 'valladolid': 'Castilla y León', 'zamora': 'Castilla y León',
        'almeria': 'Andalucía', 'cadiz': 'Andalucía', 'cordoba': 'Andalucía', 'granada': 'Andalucía',
        'huelva': 'Andalucía', 'jaen': 'Andalucía', 'malaga': 'Andalucía', 'sevilla': 'Andalucía',
        'huesca': 'Aragón', 'teruel': 'Aragón', 'zaragoza': 'Aragón',
        'asturias': 'Asturias', 'balears': 'Islas Baleares',
        'palmas': 'Canarias', 'santa_cruz_de_tenerife': 'Canarias',
        'cantabria': 'Cantabria',
        'barcelona': 'Cataluña', 'girona': 'Cataluña', 'lleida': 'Cataluña', 'tarragona': 'Cataluña',
        'alicante': 'C. Valenciana', 'castellon': 'C. Valenciana', 'valencia': 'C. Valenciana',
        'badajoz': 'Extremadura', 'caceres': 'Extremadura',
        'coruna': 'Galicia', 'lugo': 'Galicia', 'ourense': 'Galicia', 'pontevedra': 'Galicia',
        'madrid': 'Madrid', 'murcia': 'Murcia', 'navarra': 'Navarra',
        'araba': 'País Vasco', 'bizkaia': 'País Vasco', 'gipuzkoa': 'País Vasco',
        'rioja': 'La Rioja', 'ceuta': 'Ceuta', 'melilla': 'Melilla'
    }

    # ----------------------------------------------------------------------
    # 2. FILTRADO BÁSICO DE ENTIDADES NO VÁLIDAS
    # ----------------------------------------------------------------------
    def filtrar_basicos(df):
        """
        Elimina:
            - Total Nacional
            - Desconocida
            - En el extranjero
            - TOTAL grupo penal (solo en SEC)
        """
        df = df.copy()

        mask = (
            ~df['Provincias'].str.contains('Total Nacional', case=False) &
            ~df['Provincias'].str.contains('Desconocida', case=False) &
            ~df['Provincias'].str.contains('En el extranjero', case=False)
        )

        if 'Grupo penal' in df.columns:
            mask &= (df['Grupo penal'] != 'TOTAL grupo penal')

        return df[mask]

    df_h_atomo = filtrar_basicos(df_h)
    df_p_atomo = filtrar_basicos(df_p)

    # ----------------------------------------------------------------------
    # 3. NORMALIZACIÓN DE PROVINCIAS Y TIPOS PENALES
    # ----------------------------------------------------------------------
    norm = ProvinciaNormalizer()

    # Normalización de nombres de provincias (SEC + INE)
    df_h_atomo = norm.transform(df_h_atomo)
    df_p_atomo = norm.transform(df_p_atomo)

    # Normalización de tipologías penales (SEC)
    df_h_atomo['Grupo penal'] = (
        df_h_atomo['Grupo penal']
        .str.lower()
        .str.normalize('NFD')
        .str.replace(r'[\u0300-\u036f]', '', regex=True)  # quitar acentos
        .str.replace(" ", "_")                           # espacios → guiones bajos
    )

    # ----------------------------------------------------------------------
    # 4. AGREGACIÓN DE POBLACIÓN (INE)
    # ----------------------------------------------------------------------
    df_p_agrupado = (
        df_p_atomo
        .groupby(['Provincias', 'periodo'], as_index=False)['Total']
        .sum()
        .rename(columns={'Total': 'Poblacion_Provincial'})
    )

    # ----------------------------------------------------------------------
    # 5. MERGE FINAL SEC + INE
    # ----------------------------------------------------------------------
    df_master = pd.merge(
        df_h_atomo,
        df_p_agrupado,
        on=['Provincias', 'periodo'],
        how='left'
    )

    df_master.rename(columns={'Total': 'Total_Hechos'}, inplace=True)

    # ----------------------------------------------------------------------
    # 6. ASIGNACIÓN DE CCAA
    # ----------------------------------------------------------------------
    df_master['CCAA'] = df_master['Provincias'].map(mapeo_completo_ccaa)

    # ----------------------------------------------------------------------
    # 7. CÁLCULO DE LA TASA DE CRIMINALIDAD (x 1.000 habitantes)
    # ----------------------------------------------------------------------
    df_master['Tasa_Criminalidad'] = (
        df_master['Total_Hechos'] / df_master['Poblacion_Provincial']
    ) * 1000

    # Relleno de posibles nulos (casos residuales)
    df_master.fillna(0, inplace=True)

    return df_master



# ------------------------------------------------------------------------------
# 4. MÉTRICAS AVANZADAS (EDA y análisis cuantitativo)
# ------------------------------------------------------------------------------
# OBJETIVO:
# A partir del dataset maestro (SEC + INE ya unificados y normalizados),
# se generan las métricas necesarias para el análisis exploratorio:
#
#   - Código INE (para mapas y georreferenciación)
#   - Total provincial anual (base para pesos relativos)
#   - Peso por tipología penal (distribución delictiva)
#   - Peso del fraude informático (métrica específica)
#   - Variación interanual (VAR%)
#
# Devuelve un DataFrame enriquecido listo para el EDA gráfico.
# ------------------------------------------------------------------------------

def pipeline_metricas(df):

    # Se trabaja siempre sobre una copia para no modificar el dataset maestro original
    df = df.copy()

    # --------------------------------------------------------------------------
    # 1. ASIGNACIÓN DE CÓDIGOS INE (necesarios para mapas coropléticos)
    # --------------------------------------------------------------------------
    cod_prov = {
        "araba": "01", "albacete": "02", "alicante": "03", "almeria": "04", "avila": "05",
        "badajoz": "06", "balears": "07", "barcelona": "08", "burgos": "09", "caceres": "10",
        "cadiz": "11", "castellon": "12", "ciudad_real": "13", "cordoba": "14", "coruna": "15",
        "cuenca": "16", "girona": "17", "granada": "18", "guadalajara": "19", "gipuzkoa": "20",
        "huelva": "21", "huesca": "22", "jaen": "23", "leon": "24", "lleida": "25", "rioja": "26",
        "lugo": "27", "madrid": "28", "malaga": "29", "murcia": "30", "navarra": "31",
        "ourense": "32", "asturias": "33", "palencia": "34", "palmas": "35", "pontevedra": "36",
        "salamanca": "37", "santa_cruz_de_tenerife": "38", "cantabria": "39", "segovia": "40",
        "sevilla": "41", "soria": "42", "tarragona": "43", "teruel": "44", "toledo": "45",
        "valencia": "46", "valladolid": "47", "bizkaia": "48", "zamora": "49", "zaragoza": "50",
        "ceuta": "51", "melilla": "52"
    }

    df['codigo_ine'] = df['Provincias'].map(cod_prov)

    # --------------------------------------------------------------------------
    # 2. TOTAL PROVINCIAL POR AÑO
    # --------------------------------------------------------------------------
    # Necesario para calcular pesos relativos:
    #   Peso tipología = Hechos del grupo penal / Total provincial del año
    totales_prov = (
        df.groupby(['Provincias', 'periodo'])['Total_Hechos']
        .sum()
        .reset_index()
        .rename(columns={'Total_Hechos': 'Total_Provincial'})
    )

    # Unión del total provincial al dataset principal
    df = df.merge(totales_prov, on=['Provincias', 'periodo'], how='left')

    # --------------------------------------------------------------------------
    # 3. PESO POR TIPOLOGÍA PENAL (distribución delictiva)
    # --------------------------------------------------------------------------
    # Expresa qué porcentaje representa cada grupo penal dentro del total
    # de ciberdelitos de la provincia en ese año.
    df['Peso_Tipologia'] = (df['Total_Hechos'] / df['Total_Provincial']) * 100

    # --------------------------------------------------------------------------
    # 4. PESO DEL FRAUDE INFORMÁTICO (métrica específica)
    # --------------------------------------------------------------------------
    # Se calcula únicamente para el grupo penal "fraude_informatico".
    df['Peso_Fraude'] = np.where(
        df['Grupo penal'] == 'fraude_informatico',
        df['Peso_Tipologia'],
        0
    )

    # --------------------------------------------------------------------------
    # 5. VARIACIÓN INTERANUAL (VAR%)
    # --------------------------------------------------------------------------
    # Fórmula:
    #   VAR% = (H_t - H_t-1) / H_t-1 * 100
    # Se calcula por provincia y tipología penal.
    df = df.sort_values(['Provincias', 'Grupo penal', 'periodo'])

    df['VAR_pct'] = (
        df.groupby(['Provincias', 'Grupo penal'])['Total_Hechos']
        .pct_change() * 100
    )

    # --------------------------------------------------------------------------
    # 6. RETORNO DEL DATAFRAME ENRIQUECIDO
    # --------------------------------------------------------------------------
    return df



# ------------------------------------------------------------------------------
# 5. PIPELINE MAESTRO: CARGA RAW → ETL → LIMPIEZA → MÉTRICAS → EXPORTACIÓN
# ------------------------------------------------------------------------------
# OBJETIVO:
# Unificar en un único flujo todo el procesamiento necesario para generar
# el dataset maestro de cibercriminalidad (SEC + INE), completamente limpio,
# normalizado, enriquecido con métricas y listo para el análisis exploratorio.
#
# Este pipeline:
#   1. Carga los datos RAW desde los CSV originales
#   2. Ejecuta el ETL inicial (limpieza SEC + INE)
#   3. Aplica el pipeline de limpieza, normalización y merge
#   4. Calcula todas las métricas avanzadas necesarias para el EDA
#   5. Exporta un único archivo final: df_cibercrimen.csv
#
# De esta forma, si mañana se actualizan los datos del SEC o del INE,
# basta con sustituir los archivos RAW y ejecutar este pipeline completo.
# ------------------------------------------------------------------------------

def pipeline_cibercrimen(path_hechos, path_ine, output="df_cibercrimen.csv"):

    # ---------------------------------------------------------
    # 1. CARGA Y ETL DE DATOS RAW (SEC + INE)
    # ---------------------------------------------------------
    df_h, df_p = cargar_y_etl_raw(path_hechos, path_ine)

    # ---------------------------------------------------------
    # 2. LIMPIEZA, NORMALIZACIÓN Y MERGE (SEC + INE)
    # ---------------------------------------------------------
    df_master = pipeline_limpieza_hechos(df_h, df_p)

    # ---------------------------------------------------------
    # 3. CÁLCULO DE MÉTRICAS AVANZADAS (EDA)
    # ---------------------------------------------------------
    df_final = pipeline_metricas(df_master)

    # Redondeo final de tasas para presentación
    df_final['Tasa_Criminalidad'] = df_final['Tasa_Criminalidad'].round(4)

    # ---------------------------------------------------------
    # 4. EXPORTACIÓN DEL DATASET MAESTRO
    # ---------------------------------------------------------
    df_final.to_csv(output, sep=';', index=False)
    print(f"Archivo maestro generado correctamente: {output}")

    return df_final


# ------------------------------------------------------------------------------
# EJECUCIÓN DEL PIPELINE COMPLETO
# ------------------------------------------------------------------------------
df_cibercrimen = pipeline_cibercrimen("hechos_170426.csv", "ine_170426.csv")