# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKDJUGfXRINRL3a9gfUqmuYntErxUCnl
"""
import streamlit as st
import pandas as pd
import plotly.express as px
import json
import os

# Configuración inicial de la página
st.set_page_config(page_title="Cibercrimen 2025 - Dashboard Predictivo", layout="wide")

# --- FUNCIONES DE CARGA ---
@st.cache_data
def load_data():
    # Cargamos el archivo de predicciones principal
    path_pred = os.path.join("01_Data", "predicciones_cibercriminalidad_2025.csv")
    df = pd.read_csv(path_pred, sep=';') 

    # Carga de GeoJSON
    path_geo = os.path.join("01_Data", "spain-provinces.geojson")
    with open(path_geo, encoding='utf-8') as f:
        geojson = json.load(f)
    return df, geojson

def mover_canarias(geojson, dx=5.5, dy=4.5, scale=1.0):
    canarias = ["35", "38"]
    for feature in geojson["features"]:
        cod = feature["properties"]["cod_prov"]
        if cod in canarias:
            geom = feature["geometry"]
            if geom["type"] == "MultiPolygon":
                geom["coordinates"] = [[[[lon * scale + dx, lat * scale + dy] for lon, lat in ring] for ring in poly] for poly in geom["coordinates"]]
            elif geom["type"] == "Polygon":
                geom["coordinates"] = [[[lon * scale + dx, lat * scale + dy] for lon, lat in ring] for ring in geom["coordinates"]]
    return geojson

# --- INICIO DE LA APP ---
try:
    df_pred, geojson_raw = load_data()
    geojson = mover_canarias(geojson_raw)

    # Diccionario de códigos INE
    cod_prov = {
        "araba": "01", "albacete": "02", "alicante": "03", "almeria": "04", "avila": "05",
        "badajoz": "06", "balears": "07", "barcelona": "08", "burgos": "09", "caceres": "10",
        "cadiz": "11", "castellon": "12", "ciudad_real": "13", "cordoba": "14", "coruna": "15",
        "cuenca": "16", "girona": "17", "granada": "18", "guadalajara": "19", "gipuzkoa": "20",
        "huelva": "21", "huesca": "22", "jaen": "23", "leon": "24", "lleida": "25", "rioja": "26",
        "lugo": "27", "madrid": "28", "malaga": "29", "murcia": "30", "navarra": "31",
        "ourense": "32", "asturias": "33", "palencia": "34", "palmas": "35", "pontevedra": "36",
        "salamanca": "37", "santa_cruz_de_tenerife": "38", "cantabria": "39", "segovia": "40",
        "sevilla": "41", "soria": "42", "tarragona": "43", "teruel": "44", "toledo": "45",
        "valencia": "46", "valladolid": "47", "bizkaia": "48", "zamora": "49", "zaragoza": "50",
        "ceuta": "51", "melilla": "52"
    }
    df_pred['codigo_ine'] = df_pred['Provincias'].str.lower().map(cod_prov)

    # --- SIDEBAR / FILTROS ---
    st.sidebar.image("https://img.icons8.com/fluency/96/shield.png", width=80)
    st.sidebar.title("Panel de Control")

    provincia_lista = sorted(df_pred['Provincias'].unique())
    provincia_sel = st.sidebar.selectbox("📍 Seleccione Provincia:", provincia_lista)
    modo_mapa = st.sidebar.radio("🗺️ Ver en Mapa:", ["Fraude Informático", "Otros Ciberdelitos (Total)"])

    # --- CUERPO PRINCIPAL ---
    st.title("🛡️ Predicción de Cibercriminalidad 2025")
    st.markdown("Basado en el modelo de Machine Learning (Random Forest & XGBoost)")

    col_mapa, col_stats = st.columns([1.5, 1])

    with col_mapa:
        df_resumen = df_pred.groupby(['codigo_ine', 'Provincias', 'Grupo penal']).agg({
            'Tasa_Predicha_2025': 'first',
            'Hechos_Predichos_2025': 'first'
        }).reset_index()

        if modo_mapa == "Fraude Informático":
            df_plot = df_resumen[df_resumen["Grupo penal"] == "fraude_informatico"]
            titulo_mapa = "Predicción 2025: Fraude Informático (Tasa x 1.000)"
        else:
            df_plot = df_resumen[df_resumen["Grupo penal"] != "fraude_informatico"].groupby(['codigo_ine', 'Provincias']).agg({'Tasa_Predicha_2025':'sum'}).reset_index()
            titulo_mapa = "Predicción 2025: Otros Ciberdelitos"

        fig_mapa = px.choropleth(
            df_plot, geojson=geojson, locations="codigo_ine",
            featureidkey="properties.cod_prov", color="Tasa_Predicha_2025",
            hover_name="Provincias", color_continuous_scale="Plasma",
            template="plotly_dark"
        )
        fig_mapa.update_geos(fitbounds="locations", visible=False)
        fig_mapa.update_layout(margin=dict(t=50, l=0, r=0, b=0), height=500)
        st.plotly_chart(fig_mapa, use_container_width=True)

    with col_stats:
        df_prov = df_pred[df_pred['Provincias'] == provincia_sel]
        tasa_f = df_prov[df_prov['Grupo penal'] == 'fraude_informatico']['Tasa_Predicha_2025'].values[0]

        st.subheader(f"Análisis: {provincia_sel}")
        if tasa_f > 10:
            st.error(f"🔴 Riesgo Muy Alto (Tasa: {tasa_f:.2f})")
        elif tasa_f > 7:
            st.warning(f"🟡 Riesgo Moderado (Tasa: {tasa_f:.2f})")
        else:
            st.success(f"🟢 Riesgo Controlado (Tasa: {tasa_f:.2f})")

        df_radar = df_prov[df_prov['Grupo penal'] != 'fraude_informatico'].copy()
        df_radar['Grupo penal'] = df_radar['Grupo penal'].str.replace('_', ' ').str.title()

        fig_radar = px.line_polar(
            df_radar, r='Hechos_Predichos_2025', theta='Grupo penal',
            line_close=True, template="plotly_dark"
        )
        fig_radar.update_traces(fill='toself', line_color='indianred')
        fig_radar.update_layout(height=350, margin=dict(t=30, b=20, l=20, r=20))
        st.plotly_chart(fig_radar, use_container_width=True)

    # --- SECCIÓN INFERIOR: GLOSARIO Y RESUMEN (DENTRO DEL TRY) ---
    st.divider()
    
    with st.expander("📖 Glosario: ¿Qué delitos incluye cada grupo estratégico?"):
        data_clusters = {
            "Grupo Penal": ["Fraude Informático", "Interferencia", "Amenazas/Coacciones", "Delitos Sexuales", "Falsificación", "Contra el Honor", "Acceso/Interceptación", "Propiedad Ind."],
            "Delitos Incluidos": [
                "Estafas bancarias, tarjetas, cheques, inversores.",
                "Ataques a sistemas, daños y ataques a datos.",
                "Extorsión, acoso, amenazas, coacciones.",
                "Sexting, grooming, agresiones sexuales, pornografía.",
                "Usurpación civil, falsificación moneda/documentos.",
                "Injurias, calumnias, perfiles falsos.",
                "Acceso ilegal, revelación secretos, interceptación.",
                "Propiedad intelectual, espionaje industrial."
            ]
        }
        st.table(pd.DataFrame(data_clusters))

    total_2025 = int(df_prov['Hechos_Predichos_2025'].sum())
    st.info(f"💡 **Resumen Ejecutivo:** Para el año 2025, se estima un total de **{total_2025:,}** hechos conocidos en la provincia de {provincia_sel}.")

except Exception as e:
    st.error(f"Se ha producido un error: {e}")