# -*- coding: utf-8 -*-
"""test_feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpjQ1bDiA3RHqRzoqYWESGjVGGNRDszP
"""

# ==============================================================================
# TEST: Feature Engineering (feature_engineering.py)
#Comprueba que tu ingeniería de features crea las columnas clave.
#Nota hay que Ajustar el import según el nombre real de la función guardada en SRC.
# ==============================================================================

import pandas as pd
from 03_SRC.feature_engineering import aplicar_feature_engineering

def test_feature_engineering_crea_columnas():
    df = pd.DataFrame({
        "Provincias": ["Madrid", "Madrid", "Madrid"],
        "Grupo penal": ["fraude_informatico"] * 3,
        "periodo": [2022, 2023, 2024],
        "Total_Hechos": [100, 120, 140],
        "Poblacion_Provincial": [3000000] * 3
    })

    df_out = aplicar_feature_engineering(df)

    columnas_esperadas = [
        "Tasa_Criminalidad",
        "Tasa_Lag_1",
        "Tasa_Lag_2",
        "Media_Movil_2y",
        "VAR_pct"
    ]

    for col in columnas_esperadas:
        assert col in df_out.columns