# -*- coding: utf-8 -*-
"""test_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2249jxSPfNVZ0vpyabz9ssi28byyMVs
"""

# ==============================================================================
# TEST: Pipeline (model_utils.py)
# Comprueba que el pipeline se crea y entrena sin romperse.
# ==============================================================================

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from 03_SRC.model_utils import crear_pipeline

def test_pipeline_entrena():
    # Datos mock
    df = pd.DataFrame({
        "Provincias": ["Madrid", "Madrid", "Madrid"],
        "Grupo penal": ["fraude_informatico"] * 3,
        "Poblacion_Provincial": [3000000, 3000000, 3000000],
        "Peso_Fraude": [20, 22, 21],
        "VAR_pct": [5, 3, 4],
        "Tasa_Lag_1": [10, 11, 12],
        "Tasa_Lag_2": [9, 10, 11],
        "Media_Movil_2y": [9.5, 10.5, 11.5],
        "Tasa_Criminalidad": [12, 13, 14]
    })

    X = df.drop(columns=["Tasa_Criminalidad"])
    y = df["Tasa_Criminalidad"]

    modelo = RandomForestRegressor()

    pipe = crear_pipeline(modelo, "fraude")
    pipe.fit(X, y)

    pred = pipe.predict(X)
    assert len(pred) == len(X)