# -*- coding: utf-8 -*-
"""01_prep_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOIFOHGAB7b0fTMMAQHxr-2-j4jwrEgb
"""

# ETL: Preparación de Datasets de Trabajo SEC - INE (2022-2024)
# Nota: en este apartado se hará la primera transformación y limpieza
# de los archivos descargado en bruto del SEC e INE

# Importar librerias
import pandas as pd
import os

# Definición de rutas (Paths)
# Usamos un nombre de variable consistente para apuntar a la carpeta de datos
path_data = os.path.join("..", "01_Data")

# Definir funciones de limpieza
def limpiar_hechos(path_entrada):
    """Limpia puntos y filtra años para los datos del SEC."""
    df = pd.read_csv(path_entrada, sep=';', dtype=str)

    # Operación de limpieza
    # Limpieza de número español
    # elimino el . para evitar que pandas lo lea como decimal
    df['Total'] = df['Total'].str.replace('.', '', regex=False).astype(int)
    df['periodo'] = df['periodo'].astype(int)

    return df[df['periodo'].between(2022, 2024)].copy()

def limpiar_ine(path_entrada):
    """Limpia población, ajusta periodos y filtra años para el INE."""
    df = pd.read_csv(path_entrada, sep=';', dtype=str)

    # Filtrado lógico
    df = df[
        (df['Generación'] == 'Todas las edades') &
        (df['Sexo'] == 'Total') &
        (df['Periodo'].str.contains('1 de enero', na=False))
    ].copy()

    # Limpieza de valores
    df['Total'] = df['Total'].str.replace('.', '', regex=False).astype(int)
    df['periodo'] = df['Periodo'].str.extract(r'(\d{4})').astype(int) - 1

    return df[df['periodo'].between(2022, 2024)][['Provincias', 'periodo', 'Total']].copy()

if __name__ == "__main__":
    # Esta parte SOLO se ejecuta cuando haces `python 01_prep_data.py`
    # Es útil para desarrollo, pero no ensucia otros scripts.
    try:
        # Definimos las rutas completas usando path_data
        ruta_hechos_in = os.path.join(path_data, 'hechos_170426.csv')
        ruta_ine_in = os.path.join(path_data, 'ine_170426.csv')

        print(f"⏳ Iniciando procesamiento desde: {path_data}")

        # Ejecución de la limpieza
        hechos_limpios = limpiar_hechos(ruta_hechos_in)
        ine_limpio = limpiar_ine(ruta_ine_in)

        # Guardar CSV limpios en la misma carpeta 01_Data
        hechos_limpios.to_csv(os.path.join(path_data, 'hechos_22_24.csv'), sep=';', index=False)
        ine_limpio.to_csv(os.path.join(path_data, 'ine_22_24.csv'), sep=';', index=False)

        print("✅ ETL inicial completada sin errores.")
        print(f"📁 Archivos generados en {path_data}: hechos_22_24.csv e ine_22_24.csv")

    except Exception as e:
        print(f"❌ Error en la limpieza: {e}")