# -*- coding: utf-8 -*-
"""02_pipeline_cibercrimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYboC6HGaCXwbclWTwuQUMlwg9dLyPA9
"""

# Pipeline cibercrimen: Consolidación, Formateo, creación CCAA y Auditoría (2022-2024)
# En esta sección se realiza la ingesta automatizada de los archivos CSV,
# estableciendo las estructuras de datos base que serán utilizadas en el análisis posterior.
# en el notebook 03 EDA Gráfico.

# Importar librerias
import pandas as pd
import os
import re
import unicodedata
from sklearn.base import BaseEstimator, TransformerMixin

# 1. Definición de rutas (Paths)
# Usamos un nombre de variable consistente
path_data = os.path.join("..", "01_Data")

# ----------------------------------------------------------------------------
# 1. CLASE DE NORMALIZACIÓN (Arquitectura Reutilizable)
# ----------------------------------------------------------------------------
class ProvinciaNormalizer(BaseEstimator, TransformerMixin):
    """
    OBJETIVO: Estandarizar nombres de provincias (ej: '01 Araba/Álava' -> 'araba')
    para que el cruce entre las tablas sea perfecto.
    """
    def fit(self, X, y=None):
        return self

    def _norm_string(self, text):
        if not isinstance(text, str): return ""
        text = re.sub(r"^\d{2}\s+", "", text)  # Quitar códigos INE
        text = "".join(c for c in unicodedata.normalize('NFD', text)
                       if unicodedata.category(c) != 'Mn')  # Quitar acentos
        text = re.split(r'[/|(|,]', text)[0].strip().lower()  # Limpiar barras/paréntesis
        return text.replace(" ", "_")

    def transform(self, X):
        df = X.copy()
        if "Provincias" in df.columns:
            df["Provincias"] = df["Provincias"].apply(self._norm_string)
        return df


# ----------------------------------------------------------------------------
# 2. FUNCIÓN PRINCIPAL DEL PIPELINE (AJUSTADA A METODOLOGÍA 2022-2024)
# ----------------------------------------------------------------------------
def pipeline_limpieza_hechos(df_h, df_p):
    """
    Motor de unificación: Une Hechos + Población + CCAA en una sola tabla.
    """

    # --- 1. MAPEO CCAA ---
    mapeo_completo_ccaa = {
        'albacete': 'Castilla-La Mancha', 'ciudad_real': 'Castilla-La Mancha', 'cuenca': 'Castilla-La Mancha',
        'guadalajara': 'Castilla-La Mancha', 'toledo': 'Castilla-La Mancha',
        'avila': 'Castilla y León', 'burgos': 'Castilla y León', 'leon': 'Castilla y León',
        'palencia': 'Castilla y León', 'salamanca': 'Castilla y León', 'segovia': 'Castilla y León',
        'soria': 'Castilla y León', 'valladolid': 'Castilla y León', 'zamora': 'Castilla y León',
        'almeria': 'Andalucía', 'cadiz': 'Andalucía', 'cordoba': 'Andalucía', 'granada': 'Andalucía',
        'huelva': 'Andalucía', 'jaen': 'Andalucía', 'malaga': 'Andalucía', 'sevilla': 'Andalucía',
        'huesca': 'Aragón', 'teruel': 'Aragón', 'zaragoza': 'Aragón',
        'asturias': 'Asturias', 'balears': 'Islas Baleares',
        'palmas': 'Canarias', 'santa_cruz_de_tenerife': 'Canarias',
        'cantabria': 'Cantabria',
        'barcelona': 'Cataluña', 'girona': 'Cataluña', 'lleida': 'Cataluña', 'tarragona': 'Cataluña',
        'alicante': 'C. Valenciana', 'castellon': 'C. Valenciana', 'valencia': 'C. Valenciana',
        'badajoz': 'Extremadura', 'caceres': 'Extremadura',
        'coruna': 'Galicia', 'lugo': 'Galicia', 'ourense': 'Galicia', 'pontevedra': 'Galicia',
        'madrid': 'Madrid', 'murcia': 'Murcia', 'navarra': 'Navarra',
        'araba': 'País Vasco', 'bizkaia': 'País Vasco', 'gipuzkoa': 'País Vasco',
        'rioja': 'La Rioja', 'ceuta': 'Ceuta', 'melilla': 'Melilla'
    }

    # --- 2. FILTRADO ---
    def filtrar_basicos(df):
        df = df.copy()
        mask = (
            ~df['Provincias'].str.contains('Total Nacional', case=False) &
            ~df['Provincias'].str.contains('Desconocida', case=False) &
            ~df['Provincias'].str.contains('En el extranjero', case=False)
        )
        if 'Grupo penal' in df.columns:
            mask &= (df['Grupo penal'] != 'TOTAL grupo penal')
        return df[mask]

    df_h_atomo = filtrar_basicos(df_h)
    df_p_atomo = filtrar_basicos(df_p)

    # --- 3. NORMALIZACIÓN ---
    norm = ProvinciaNormalizer()
    df_h_atomo = norm.transform(df_h_atomo)
    df_p_atomo = norm.transform(df_p_atomo)

    # Normalizar delitos
    df_h_atomo['Grupo penal'] = (
        df_h_atomo['Grupo penal']
        .str.lower()
        .str.normalize('NFD')
        .str.replace(r'[\u0300-\u036f]', '', regex=True)
        .str.replace(" ", "_")
    )

    # --- 4. AGREGACIÓN POBLACIÓN ---
    df_p_agrupado = df_p_atomo.groupby(['Provincias', 'periodo'], as_index=False)['Total'].sum()
    df_p_agrupado.rename(columns={'Total': 'Poblacion_Provincial'}, inplace=True)

    # --- 5. MERGE FINAL ---
    df_master = pd.merge(df_h_atomo, df_p_agrupado,
                         on=['Provincias', 'periodo'], how='left')
    df_master.rename(columns={'Total': 'Total_Hechos'}, inplace=True)

    # --- 6. CREACIÓN DE CCAA ---
    df_master['CCAA'] = df_master['Provincias'].map(mapeo_completo_ccaa)

    # --- 7. MÉTRICAS (CORREGIDO A X 1.000 SEGÚN SEC) ---
    df_master['Tasa_Criminalidad'] = (
        df_master['Total_Hechos'] / df_master['Poblacion_Provincial']
    ) * 1000

    df_master.fillna(0, inplace=True)

    return df_master


# ----------------------------------------------------------------------------
# 3. EJECUCIÓN, FORMATEO Y AUDITORÍA
# ----------------------------------------------------------------------------
if __name__ == "__main__":
    try:
        # Carga de los datasets limpios del paso anterior
        df_hechos = pd.read_csv(os.path.join(path_data, 'hechos_22_24.csv'), sep=';')
        df_poblacion = pd.read_csv(os.path.join(path_data, 'ine_22_24.csv'), sep=';')

        print(f"✅ Éxito: Archivos cargados correctamente desde {path_data}")

        # Procesamiento
        df_cibercrimen = pipeline_limpieza_hechos(df_hechos, df_poblacion)

        # Redondeo final
        df_cibercrimen['Tasa_Criminalidad'] = df_cibercrimen['Tasa_Criminalidad'].round(4)

        print(f"✅ Dataset Maestro creado con éxito (2022-2024). Filas: {len(df_cibercrimen)}")

        # Auditoría Técnica
        print("\n" + "="*50)
        print("🔍 AUDITORÍA FINAL DE VOLUMEN")
        print("="*50)
        sum_hechos = df_cibercrimen['Total_Hechos'].sum()
        print(f"🔹 Suma Total de HECHOS: {sum_hechos:,.0f}".replace(",", "."))

        # Exportación final
        ruta_salida = os.path.join(path_data, "df_cibercrimen.csv")
        df_cibercrimen.to_csv(ruta_salida, index=False, sep=';')

        print(f"\n✅ Archivo actualizado en: {ruta_salida}")
        print("💾 Archivo 'df_cibercrimen.csv' generado. Todo listo para Notebook 03.")

    except Exception as e:
        print(f"❌ Error al procesar el pipeline: {e}")