# -*- coding: utf-8 -*-
"""03_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pf_IDPGz2X1JlSAcNCSg_-6Sx2rfkC2
"""

#==============================================================================
# @title Carga y preparación de los datos CON MÉTRICAS PARA ANÁLISIS GRÁFICO
#==============================================================================
# En esta sección se realiza la ingesta automatizada del archivo CSV,
# que será utilizado en el análisis posterior.
#==============================================================================

import pandas as pd
import numpy as np
import os

# --- CONFIGURACIÓN DE RUTAS Y CARGA DE DATOS ---
path_data = os.path.join("..", "01_Data")
archivo_maestro = "df_cibercrimen.csv"
ruta_final = os.path.join(path_data, archivo_maestro)

def calcular_metricas_cibercrimen(df):
    """
    Calcula pesos por tipología, variaciones interanuales y métricas por CCAA.
    """
    # Crear copia de trabajo
    df_metrics = df.copy()

    # Configuración de códigos INE
    cod_prov = {
        "araba": "01", "albacete": "02", "alicante": "03", "almeria": "04", "avila": "05",
        "badajoz": "06", "balears": "07", "barcelona": "08", "burgos": "09", "caceres": "10",
        "cadiz": "11", "castellon": "12", "ciudad_real": "13", "cordoba": "14", "coruna": "15",
        "cuenca": "16", "girona": "17", "granada": "18", "guadalajara": "19", "gipuzkoa": "20",
        "huelva": "21", "huesca": "22", "jaen": "23", "leon": "24", "lleida": "25", "rioja": "26",
        "lugo": "27", "madrid": "28", "malaga": "29", "murcia": "30", "navarra": "31",
        "ourense": "32", "asturias": "33", "palencia": "34", "palmas": "35", "pontevedra": "36",
        "salamanca": "37", "santa_cruz_de_tenerife": "38", "cantabria": "39", "segovia": "40",
        "sevilla": "41", "soria": "42", "tarragona": "43", "teruel": "44", "toledo": "45",
        "valencia": "46", "valladolid": "47", "bizkaia": "48", "zamora": "49", "zaragoza": "50",
        "ceuta": "51", "melilla": "52"
    }
    df_metrics['codigo_ine'] = df_metrics['Provincias'].map(cod_prov)

    # --- CÁLCULO DE MÉTRICAS ---
    # Peso por Tipología Penal
    totales_prov = (
        df_metrics.groupby(['Provincias', 'periodo'])['Total_Hechos']
        .sum().reset_index()
        .rename(columns={'Total_Hechos': 'Total_Provincial'})
    )
    df_metrics = df_metrics.merge(totales_prov, on=['Provincias', 'periodo'], how='left')
    df_metrics['Peso_Tipologia'] = (df_metrics['Total_Hechos'] / df_metrics['Total_Provincial']) * 100

    # Peso del Fraude
    df_metrics['Peso_Fraude'] = np.where(
        df_metrics['Grupo penal'] == 'fraude_informatico',
        (df_metrics['Total_Hechos'] / df_metrics['Total_Provincial']) * 100,
        np.nan
    )

    # Variación Interanual (VAR%)
    df_metrics = df_metrics.sort_values(['Provincias', 'Grupo penal', 'periodo'])
    df_metrics['VAR_pct'] = df_metrics.groupby(['Provincias', 'Grupo penal'])['Total_Hechos'].pct_change() * 100

    return df_metrics

def generar_datasets_especificos(df_metrics):
    """
    Divide el dataset en Fraude, Otros detalles y Resumen Global de Otros.
    """
    # Separación por tipología
    df_fraude_csv = df_metrics[df_metrics["Grupo penal"] == "fraude_informatico"].copy()
    df_otros_detalle_csv = df_metrics[df_metrics["Grupo penal"] != "fraude_informatico"].copy()

    # Selección de columnas
    cols_fraude = ["codigo_ine","Provincias", "Grupo penal", "periodo", "Total_Hechos",
                   "Poblacion_Provincial", "CCAA", "Tasa_Criminalidad", "Peso_Fraude", "VAR_pct"]
    cols_otros = ["codigo_ine","Provincias", "Grupo penal", "periodo", "Total_Hechos",
                  "Poblacion_Provincial", "CCAA", "Tasa_Criminalidad", "Peso_Tipologia"]

    df_fraude_csv = df_fraude_csv[cols_fraude]
    df_otros_detalle_csv = df_otros_detalle_csv[cols_otros]

    # Resumen Global Otros
    df_global_otros_csv = df_otros_detalle_csv.groupby(["codigo_ine", "Provincias", "periodo", "CCAA"]).agg({
        "Total_Hechos": "sum",
        "Poblacion_Provincial": "first"
    }).reset_index()

    df_global_otros_csv.rename(columns={"Total_Hechos": "Total_Ciberdelitos_Global"}, inplace=True)
    df_global_otros_csv["Tasa_Global"] = (df_global_otros_csv["Total_Ciberdelitos_Global"] / df_global_otros_csv["Poblacion_Provincial"]) * 1000

    return df_fraude_csv, df_otros_detalle_csv, df_global_otros_csv

# --- BLOQUE DE EJECUCIÓN ---
if __name__ == "__main__":
    try:
        # 1. Carga
        df_maestro = pd.read_csv(ruta_final, sep=';')
        print(f"✅ Éxito: Dataset Maestro cargado desde {ruta_final}")

        # 2. Procesamiento de métricas
        df_full_metrics = calcular_metricas_cibercrimen(df_maestro)

        # 3. Generación de datasets
        df_fraude, df_otros, df_global_otros = generar_datasets_especificos(df_full_metrics)

        # 4. Exportación
        df_full_metrics.to_csv(os.path.join(path_data, "df_metrics.csv"), index=False, sep=';')
        df_fraude.to_csv(os.path.join(path_data, "datos_fraude.csv"), index=False, sep=';')
        df_otros.to_csv(os.path.join(path_data, "datos_otros.csv"), index=False, sep=';')
        df_global_otros.to_csv(os.path.join(path_data, "datos_global_otros.csv"), index=False, sep=';')

        # --- AUDITORÍA FINAL ---
        print("\n" + "="*50)
        print("🔍 AUDITORÍA DE DATOS")
        print("="*50)
        print(f"🔹 Filas procesadas: {df_full_metrics.shape[0]}")
        print(f"🔹 Suma HECHOS: {df_full_metrics['Total_Hechos'].sum():>12,.0f}".replace(",", "."))
        print(f"🔹 Datasets generados en {path_data}:")
        print("   - df_metrics.csv\n   - datos_fraude.csv\n   - datos_otros.csv\n   - datos_global_otros.csv")
        print("="*50)

    except Exception as e:
        print(f"❌ Error durante el procesamiento de métricas: {e}")