# -*- coding: utf-8 -*-
"""04_feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwSMMMVk1hlsUDWr7n7MA1xp8BfeMLwi
"""

# ==============================================================================
# @title 3. Ingeniería de Características (Feature Engineering)
# ==============================================================================
# En esta fase doto de "memoria" al modelo. Separo la lógica para
# Fraude y Otros Ciberdelitos debido a sus diferentes densidades de datos.
# ==============================================================================

import pandas as pd
import os

# --- CONFIGURACIÓN DE RUTAS ---
path_data = os.path.join("..", "01_Data")

def cargar_datasets_segmentados():
    """Realiza la ingesta de los archivos generados en la fase de métricas."""
    read_params = {
        'sep': ';',
        'encoding': 'utf-8-sig',
        'dtype': {'codigo_ine': str}
    }

    try:
        df_f = pd.read_csv(os.path.join(path_data, "datos_fraude.csv"), **read_params)
        df_o = pd.read_csv(os.path.join(path_data, "datos_otros.csv"), **read_params)
        return df_f, df_o
    except FileNotFoundError:
        raise FileNotFoundError(f"❌ No se han encontrado los archivos en {path_data}")

def aplicar_ingenieria_fraude(df):
    """Ingeniería para FRAUDE (Alta Densidad): Lags T-1, T-2 y Media Móvil."""
    df_ml = df.copy()

    # Ordeno cronológicamente por Provincia y Año
    df_ml = df_ml.sort_values(['Provincias', 'periodo'])

    # Creo Lags (T-1, T-2)
    grouped = df_ml.groupby('Provincias')['Tasa_Criminalidad']
    df_ml['Tasa_Lag_1'] = grouped.shift(1)
    df_ml['Tasa_Lag_2'] = grouped.shift(2)

    # Media móvil de 2 años basada en el pasado (evita Data Leakage)
    df_ml['Media_Movil_2y'] = df_ml.groupby('Provincias')['Tasa_Lag_1'] \
        .transform(lambda x: x.rolling(window=2, min_periods=1).mean())

    return df_ml

def aplicar_ingenieria_otros(df):
    """Ingeniería para OTROS (Baja Densidad): Solo Lag T-1."""
    df_ml = df.copy()

    # Ordeno por Provincia, Grupo Penal y Año
    df_ml = df_ml.sort_values(['Provincias', 'Grupo penal', 'periodo'])

    # Solo creo Lag_1 para evitar perder demasiados registros
    df_ml['Tasa_Lag_1'] = df_ml.groupby(['Provincias', 'Grupo penal'])['Tasa_Criminalidad'].shift(1)

    return df_ml

def limpieza_post_ingenieria(df_f, df_o):
    """Eliminación de NaNs estructurales y selección final de columnas."""

    # 1. Dropna: El año 2022 se queda sin "año anterior" y genera nulos
    df_f = df_f.dropna(subset=['Tasa_Lag_1']).copy()
    df_o = df_o.dropna(subset=['Tasa_Lag_1']).copy()

    # 2. Relleno estratégico: Si Lag_2 es nulo (año 2023), uso Lag_1
    df_f['Tasa_Lag_2'] = df_f['Tasa_Lag_2'].fillna(df_f['Tasa_Lag_1'])

    # 3. Selección final: Elimino redundancias para evitar multicolinealidad
    cols_to_drop = ['CCAA', 'codigo_ine', 'Total_Hechos']
    df_f = df_f.drop(columns=cols_to_drop)
    df_o = df_o.drop(columns=cols_to_drop)

    return df_f, df_o

# --- BLOQUE DE EJECUCIÓN ---
if __name__ == "__main__":
    try:
        # 1. Carga y Auditoría inicial
        df_fraude, df_otros = cargar_datasets_segmentados()
        print("✅ Datasets cargados correctamente.")

        # 2. Aplicar ingeniería
        df_ml_fraude = aplicar_ingenieria_fraude(df_fraude)
        df_ml_otros = aplicar_ingenieria_otros(df_otros)

        # 3. Limpieza final
        df_ml_fraude_final, df_ml_otros_final = limpieza_post_ingenieria(df_ml_fraude, df_ml_otros)

        # 4. Exportación de los datasets listos para el modelo
        df_ml_fraude_final.to_csv(os.path.join(path_data, "df_ml_fraude.csv"), index=False, sep=';')
        df_ml_otros_final.to_csv(os.path.join(path_data, "df_ml_otros.csv"), index=False, sep=';')

        # 5. Auditoría final
        print("\n" + "="*50)
        print("🔍 RESUMEN POST-INGENIERÍA")
        print("="*50)
        print(f"📊 Registros Fraude: {df_ml_fraude_final.shape[0]} (Se descarta 2022)")
        print(f"📊 Registros Otros:  {df_ml_otros_final.shape[0]} (Se descarta 2022)")
        print(f"✅ Archivos listos en {path_data}: 'df_ml_fraude.csv' y 'df_ml_otros.csv'")
        print("="*50)

    except Exception as e:
        print(f"❌ Error en el Feature Engineering: {e}")