# -*- coding: utf-8 -*-
"""05_feature_ml_cibercriminalidad_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABu28tGJDzn1Q9TjmYEVEQiUEURKYCep
"""

# -*- coding: utf-8 -*-
"""
Script 04: Ingeniería de Características y Modelado Predictivo
Este script automatiza la creación de Lags, el entrenamiento de Random Forest/XGBoost
y la exportación de modelos (.joblib) y predicciones (.csv).
"""

import os
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import OneHotEncoder, RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# ==============================================================================
# 1. CONFIGURACIÓN DE RUTAS Y CARGA
# ==============================================================================
PATH_DATA = "../01_Data/"
PATH_MODELS = "../04_ml_project/"

def cargar_datos():
    df_fraude = pd.read_csv(os.path.join(PATH_DATA, "datos_fraude.csv"), sep=';', encoding='utf-8-sig')
    df_otros = pd.read_csv(os.path.join(PATH_DATA, "datos_otros.csv"), sep=';', encoding='utf-8-sig')
    return df_fraude, df_otros

# ==============================================================================
# 2. INGENIERÍA DE CARACTERÍSTICAS (LAGS Y MEMORIA)
# ==============================================================================
def preparar_datasets(df_fraude, df_otros):
    # --- Ingeniería para FRAUDE ---
    df_f = df_fraude.sort_values(['Provincias', 'periodo']).copy()
    grouped_f = df_f.groupby('Provincias')['Tasa_Criminalidad']
    df_f['Tasa_Lag_1'] = grouped_f.shift(1)
    df_f['Tasa_Lag_2'] = grouped_f.shift(2)
    df_f['Media_Movil_2y'] = df_f.groupby('Provincias')['Tasa_Lag_1'].transform(lambda x: x.rolling(2, min_periods=1).mean())

    # --- Ingeniería para OTROS ---
    df_o = df_otros.sort_values(['Provincias', 'Grupo penal', 'periodo']).copy()
    df_o['Tasa_Lag_1'] = df_o.groupby(['Provincias', 'Grupo penal'])['Tasa_Criminalidad'].shift(1)

    # Limpieza de nulos por Lags (elimina 2022)
    df_f = df_f.dropna(subset=['Tasa_Lag_1']).fillna(method='bfill')
    df_o = df_o.dropna(subset=['Tasa_Lag_1'])

    # Selección de columnas finales[cite: 4]
    cols_drop = ['CCAA', 'codigo_ine', 'Total_Hechos']
    return df_f.drop(columns=cols_drop), df_o.drop(columns=cols_drop)

# ==============================================================================
# 3. CONSTRUCCIÓN DE PIPELINES
# ==============================================================================
def crear_pipeline(modelo, tipo):
    if tipo == "fraude":
        var_num = ['Poblacion_Provincial', 'Peso_Fraude', 'VAR_pct', 'Tasa_Lag_1', 'Tasa_Lag_2', 'Media_Movil_2y']
        var_cat = ['Provincias']
    else:
        var_num = ['Poblacion_Provincial', 'Peso_Tipologia', 'Tasa_Lag_1']
        var_cat = ['Provincias', 'Grupo penal']

    preprocessor = ColumnTransformer([
        ('num', RobustScaler(), var_num),
        ('cat', OneHotEncoder(handle_unknown='ignore'), var_cat)
    ])
    return Pipeline([('preprocessor', preprocessor), ('regressor', modelo)])

# ==============================================================================
# 4. ENTRENAMIENTO Y PROYECCIÓN 2025
# ==============================================================================
def entrenar_y_predecir(df, modelo, tipo):
    # Entrenar con todo el histórico (2023-2024)
    X = df.drop(columns=['Tasa_Criminalidad'])
    y = df['Tasa_Criminalidad']

    pipeline = crear_pipeline(modelo, tipo)
    pipeline.fit(X, y)

    # Crear input para 2025 basado en 2024
    df_2025 = df[df['periodo'] == 2024].copy()
    if tipo == "fraude":
        df_2025['Tasa_Lag_2'] = df_2025['Tasa_Lag_1']
        df_2025['Media_Movil_2y'] = (df_2025['Tasa_Criminalidad'] + df_2025['Tasa_Lag_1']) / 2

    df_2025['Tasa_Lag_1'] = df_2025['Tasa_Criminalidad']
    df_2025['periodo'] = 2025

    X_2025 = df_2025.drop(columns=['Tasa_Criminalidad'])
    df_2025['Tasa_Predicha_2025'] = pipeline.predict(X_2025)
    df_2025['Hechos_Predichos_2025'] = (df_2025['Tasa_Predicha_2025'] * df_2025['Poblacion_Provincial'] / 1000).round(0)

    return df_2025, pipeline

# ==============================================================================
# EXECUCIÓN PRINCIPAL
# ==============================================================================
if __name__ == "__main__":
    df_f, df_o = cargar_datos()
    df_ml_f, df_ml_o = preparar_datasets(df_f, df_o)

    # Modelos Ganadores del WAPE
    rf_fraude = RandomForestRegressor(n_estimators=100, random_state=42)
    xgb_otros = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)

    # Generar resultados
    res_f, pipe_f = entrenar_y_predecir(df_ml_f, rf_fraude, "fraude")
    res_o, pipe_o = entrenar_y_predecir(df_ml_o, xgb_otros, "otros")

    # Exportar Predicciones Consolidadas
    df_final = pd.concat([res_f, res_o], ignore_index=True)
    df_final.to_csv(os.path.join(PATH_DATA, "predicciones_cibercriminalidad_2025.csv"),
                    sep=';', index=False, encoding='utf-8-sig')

    # Exportar Modelos (.joblib)
    joblib.dump(pipe_f, os.path.join(PATH_MODELS, "modelo_final_fraude_2025.joblib"))
    joblib.dump(pipe_o, os.path.join(PATH_MODELS, "modelo_final_otros_2025.joblib"))

    print("✅ Proceso completado: Modelos y Predicciones 2025 guardados.")