# -*- coding: utf-8 -*-
"""app_cibercrimen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bsUhnoil8U-aKDX4y4f8sm9T01Aa-Ke
"""

# ---------------------------------------------------------
# app_cibercrimen.py
# Dashboard · Denuncias por Cibercriminalidad
# ---------------------------------------------------------


#IMPORTAR LIBRERIAS
# ---------------------------------------------------------
import streamlit as st
import pandas as pd
import joblib
import os
import sys
import importlib
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import json


# ==============================================================================
# ESTRATEGIA DE RUTAS DINÁMICAS (Portabilidad)
# Crea rutas relativas al proyecto
# Objetivo: Evitar errores de "ModuleNotFoundError" en VS Code y asegurar
# compatibilidad total al subir el código a repositorios (GitHub/CI-CD).
# ==============================================================================

# 1. Obtenemos la ruta absoluta de este script. __file__ permite que el código
# sea independiente de la ubicación del proyecto en el disco duro del usuario.
current_dir = os.path.dirname(os.path.abspath(__file__))

# 2. Subimos un nivel (..) para posicionarnos en la raíz.
# Esto estandariza la ruta base del proyecto sin importar el sistema operativo.
root_dir = os.path.abspath(os.path.join(current_dir, ".."))

# 3. Inyectamos la raíz en sys.path. Esto le dice a Python: "Busca mis módulos
# personalizados empezando por esta carpeta raíz". El insert(0, ...) da máxima
# prioridad a nuestro proyecto frente a librerías instaladas en el sistema.
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)

# ---------------------------------------------------------
# FUNCIONES DE UTILIDAD (PRINCIPIO DRY)
#"código DRY" (Don't Repeat Yourself)
# ---------------------------------------------------------
# Esta función permite reutilizar el formato de números en todas las tablas
# sin tener que reescribir la lógica en cada pestaña.
def formato_es(x):
    return f"{x:,.0f}".replace(",", ".")

# Función para la visualización de los graficos evolutivos
def plot_evolucion(df_plot, title, y_label, color_real, color_pred):
    # 1. Preparación de datos
    df_plot = df_plot.copy()
    
    # Crear la columna formateada con punto para miles
    # El formato :.0f asegura que no haya decimales y use punto como separador
    df_plot["Total_Hechos_Str"] = df_plot["Total_Hechos"].apply(lambda x: f"{int(x):,}".replace(",", "."))
    
    df_plot["periodo"] = df_plot["periodo"].astype(str)
    df_plot = df_plot.sort_values("periodo")
    
    fig = go.Figure()

    # 2. Separamos datos para las trazas
    real = df_plot[df_plot["Tipo_periodo"] == "Real"]
    pred = df_plot[df_plot["Tipo_periodo"] == "Predicción"]

    # 3. Traza REAL
    fig.add_trace(go.Scatter(
        x=real["periodo"], 
        y=real["Total_Hechos"],
        customdata=real["Total_Hechos_Str"],
        mode="lines+markers", 
        name="Real (2022–2024)",
        line=dict(color=color_real, width=3),
        hovertemplate="%{customdata}<extra></extra>"
    ))

    # 4. Traza PREDICCIÓN (Forzamos la unión con el último punto real)
    last_real = real.iloc[-1:] 
    pred_con_conexion = pd.concat([last_real, pred])

    fig.add_trace(go.Scatter(
        x=pred_con_conexion["periodo"], 
        y=pred_con_conexion["Total_Hechos"],
        customdata=pred_con_conexion["Total_Hechos_Str"],
        mode="lines+markers", 
        name="Predicción 2025",
        line=dict(color=color_pred, width=3, dash="dash"),
        hovertemplate="%{customdata}<extra></extra>"
    ))

    # 5. Ajustes finales
    fig.update_xaxes(type='category')
    fig.update_layout(
        title=title, 
        xaxis_title="Año", 
        yaxis=dict(
            title=y_label,
            # Forzamos los ticks del eje Y para que coincidan con nuestro formato
            tickformat=".,.0f" 
        ),
        showlegend=True,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        hovermode="x unified"
    )
    
    return fig

#Funciòn para los mapas mueve Canarias para que se visualice mejor el mapa
def mover_canarias(geojson, dx=5.5, dy=4.5, scale=1.0):
    canarias = ["35", "38"]

    for feature in geojson["features"]:
        cod = feature["properties"]["cod_prov"]
        geom = feature["geometry"]

        if cod in canarias:
            if geom["type"] == "Polygon":
                geom["coordinates"] = [
                    [[lon * scale + dx, lat * scale + dy] for lon, lat in ring]
                    for ring in geom["coordinates"]
                ]

            elif geom["type"] == "MultiPolygon":
                geom["coordinates"] = [
                    [
                        [[lon * scale + dx, lat * scale + dy] for lon, lat in ring]
                        for ring in poly
                    ]
                    for poly in geom["coordinates"]
                ]

    return geojson

# ---------------------------------------------------------
# CARGA DE DATOS --- CARGA DINÁMICA CON VALIDACIÓN ---
# ---------------------------------------------------------
# @st.cache_data es un decorador de Python que almacena en caché el resultado
# de la función. Esto evita que Streamlit vuelva a procesar datos pesados
# (como leer CSVs o GeoJSONs) en cada interacción del usuario, optimizando
# drásticamente el rendimiento y la velocidad de carga de la App.

@st.cache_data
def load_data():
    # 1. Defino las rutas según la estructura del proyecto usando os.path.join
    process_dir = os.path.join(root_dir, "01_Data", "Process")
    pred_dir = os.path.join(root_dir, "01_Data", "Predictions")

    # 2. Rutas específicas a los archivos
    path_real = os.path.join(process_dir, "df_cibercrimen.csv")
    path_pred = os.path.join(pred_dir, "df_cibercrimen_predicciones_2025.csv")

    # 3. Validación de seguridad: comprubeo si los archivos existen antes de leer.
    # st.stop() es clave: detiene el script evitando errores en cascada (FileNotFoundError).
    for path in [path_real, path_pred]:
        if not os.path.exists(path):
            st.error(f"Error crítico: No se encuentra el archivo en la ruta: {path}")
            st.stop()

    # 4. Carga de los datos una vez confirmada su existencia
    df_real = pd.read_csv(path_real, sep=";")
    df_pred = pd.read_csv(path_pred, sep=";")

    # 5. Normalización: Limpio espacios y paso a minúsculas para asegurar
    # que los merges o filtros no fallen por diferencias de formato (ej: 'Madrid' vs 'madrid')
    for df in [df_real, df_pred]:
        df["Provincias"] = df["Provincias"].str.strip().str.lower()
        # Limpieza de código INE para asegurar formato "02", "03"...
        df["codigo_ine"] = df["codigo_ine"].astype(str).str.replace(r'\.0$', '', regex=True)
        df["codigo_ine"] = df["codigo_ine"].str.zfill(2)
        # Forzamos a object para que sea el tipo de dato que espera Plotly
        df["codigo_ine"] = df["codigo_ine"].astype(object)

    # 6. Etiquetado: Marco el origen de los datos para diferenciarlos en los gráficos
    df_real["Tipo_periodo"] = "Real"
    df_pred["Tipo_periodo"] = "Predicción"

    # 7. Unificación: Concateno ambos datasets en uno solo (DataFrame largo)
    # y transformo 'periodo' a string para evitar los ejes con decimales
    
    # Aseguramos nombres consistentes antes del concat
    df_real = df_real.rename(columns={'Provincias': 'Provincias'})
    df_pred = df_pred.rename(columns={'Provincias': 'Provincias'})
    
    df = pd.concat([df_real, df_pred], ignore_index=True)
    
    # IMPORTANTE: Convertimos a String para que Plotly trate los años como categorías
    df["periodo"] = df["periodo"].astype(str)

    return df


@st.cache_data
def load_geojson():
    # === VALIDACIÓN GEOJSON ===
    process_dir = os.path.join(root_dir, "01_Data", "Process")
    path_geo = os.path.join(process_dir, "spain-provinces.geojson")

    if not os.path.exists(path_geo):
        st.error(f"Error crítico: Falta el archivo de mapas en {path_geo}")
        st.stop()

    # Carga del JSON de provincias
    with open(path_geo, "r", encoding="utf-8") as f:
        geo_data = json.load(f)

# FORZAR: Asegurar que todos los IDs en el GeoJSON sean strings de 2 dígitos
    for feature in geo_data["features"]:
        cod = str(feature["properties"].get("cod_prov", ""))
        feature["properties"]["cod_prov"] = cod.zfill(2)

    return mover_canarias(geo_data)

# ---------------------------------------------------------
# CONFIGURACIÓN GENERAL  DE LA APP Y TÍTULO
# Orden y flujo de trabajo: Configuración → Carga de datos
# → Título visual → Pestañas.
# ---------------------------------------------------------
st.set_page_config(
    page_title="Predicción de Denuncias por Cibercriminalidad en España (2025)",
    layout="wide",
    initial_sidebar_state="expanded"
)
# CARGA DE DATOS (Se ejecuta al iniciar la App)
df = load_data()
geojson = load_geojson()

# ---------------------------------------------------------
# TÍTULO PRINCIPAL
# ENCABEZADO VISUAL (Lo que el usuario ve)
# Se usa un contenedor para que el encabezado esté siempre visible
# ---------------------------------------------------------

with st.container():
    col1, col2 = st.columns([3, 1])
    with col1:
        st.title("Predicción de Denuncias por Cibercriminalidad en España (2025)")
        st.caption("Histórico 2022–2024 · Datos oficiales SEC · Nivel provincial")
    with col2:
        st.info("Actualización: Mayo 2026")


# ---------------------------------------------------------
# PESTAÑAS de la APP (cada tab es una pestaña)
# ---------------------------------------------------------

tab1, tab2, tab3, tab4 = st.tabs([
    "Introducción",
    "Evolución Nacional",
    "Predicción Fraude Informático 2025",
    "Predicción Otros Ciberdelitos 2025"
])
# ---------------------------------------------------------
# TAB 1 — INTRODUCCIÓN
# ---------------------------------------------------------
with tab1:
    st.header("Introducción y Contexto del Proyecto")
    st.markdown("""
    Este dashboard muestra la evolución de las **denuncias por cibercriminalidad** registradas en el
    **Sistema Estadístico de Criminalidad (SEC)** entre **2022 y 2024**, junto con una **predicción para 2025**
    generada mediante modelos de Machine Learning.

    **Importante:**
    - Los datos del SEC son **anuales**, por lo que no existe estacionalidad.
    - El SEC suele actualizar con retraso, por lo que **2025 aún no está disponible de forma desglosada**.
    - La predicción 2025 es **estática**, basada en el histórico 2022–2024.
    - la comparación debe realizarse únicamente con el bloque
    **“Cibercriminalidad (infracciones penales cometidas por medio ciber)”** del ámbito nacional,
    excluyendo el apartado **“En el extranjero”** (pág. 507 del informe del SEC).
    """)
    st.divider() # Esto añade una línea horizontal sutil y elegante para separar secciones

     # =========================
    # 3) Validación datos y proyectado 2025
    # =========================
    st.subheader("Validación del modelo con datos oficiales del SEC (2025)")

    # Crear el DataFrame (esto está perfecto)
    df_val = pd.DataFrame({
        "Indicador": ["Total Cibercrimen", "Fraude informático", "Otros ciberdelitos"],
        "SEC 2025": [489248, 430493, 58755],
        "Modelo 2025": [503812, 447118, 56694],
        "Desviación (%)": ["+2,97", "+3,86", "-3,50"],
    })

    # LLAMO A LA FUNCIÓN DEFINIDA AL INICIO DEL SCRIPT
    # El diccionario de formato ahora llama directamente a la función global 'formato_es'.

    st.table(df_val.style.format({
        "SEC 2025": formato_es,
        "Modelo 2025": formato_es
    }))

    st.markdown("""
    - Desviación global ≈ **3 %**.
    - Ajuste superior al **96 %** en ambas tipologías.
    - Comparación realizada solo sobre **ámbito nacional provincial**, excluyendo “En el extranjero”.
    """)

    st.divider() # Esto añade una línea horizontal sutil y elegante para separar secciones
    # =========================
    # Clústeres (glosario)
    # =========================
    st.subheader("Glosario de Tipologías del SEC")
    st.caption("Clasificación oficial del Sistema Estadístico de Criminalidad")

    glosario = {
        "Grupo penal": [
            "fraude_informatico",
            "interferencia_en_los_datos_y_en_el_sistema",
            "amenazas_y_coacciones",
            "delitos_sexuales",
            "falsificacion_informatica",
            "contra_el_honor",
            "acceso_e_interceptacion_ilicita",
            "contra_la_propiedad_industrial_intelectual",
        ],
        "Descripción": [
            "Estafas y fraude económico digital (Estafas bancarias, tarjetas, cheques, inversores).",
            "Ataques a datos y sistemas; sabotaje digital.",
            "Amenazas, extorsión, coacciones y acoso.",
            "Sexting, grooming, pornografía de menores, agresiones sexuales.",
            "Usurpación de identidad y falsificación digital/documental.",
            "Injurias, calumnias, perfiles falsos y hostigamiento mediante tecnologías.",
            "Acceso ilegal, revelación de secretos e intrusismo.",
            "Delitos contra propiedad industrial/intelectual, espionaje industrial y mercado.",
        ],
    }

    st.table(pd.DataFrame(glosario))

    st.divider() # Esto añade una línea horizontal sutil y elegante para separar secciones
    # =========================
    # 2) Métricas
    # =========================
    st.subheader("Métricas utilizadas en el análisis")
    st.caption("Definidas y validadas en el Notebook 01 – Validación del modelo.")

    st.markdown("""
    - **Total de hechos:** volumen real de denuncias por provincia, año y grupo penal.
    - **Tasa de criminalidad (por 1.000 hab.):** normaliza por población para comparar provincias, independientemente del tamaño demográfico.
    - **Distribución por tipología penal:** peso (%) de cada grupo penal dentro del total provincial de ciberdelitos.
    - **Peso del fraude:** porcentaje que representa el fraude informático sobre el total de ciberdelitos en cada provincia.
    - **Variación interanual (VAR%):** crecimiento o descenso relativo respecto al año anterior (solo aplicable a fraude informático).
    - **Δ Tasa (puntos por 1.000 hab.):** cambio absoluto en la tasa entre 2024 y 2025; útil para tipologías con incidencia baja.
    - **Ranking por intensidad:** ordenación de provincias según su tasa de criminalidad (nivel de incidencia).

    """)
    st.divider() # Esto añade una línea horizontal sutil y elegante para separar secciones

    # =========================
    # 4) Fuentes oficiales
    # =========================
    st.subheader("Fuentes oficiales")

    st.markdown("""
    - **SEC – Sistema Estadístico de Criminalidad** Portal estadístico del Ministerio del Interior.
    - **Balance de Criminalidad 2025 (4º trimestre)** Informe oficial utilizado para la validación de 2025.
    - **INE – Instituto Nacional de Estadística** Población residente por provincia (Estadística continua de población) para el cálculo de tasas.
    """)

# ---------------------------------------------------------
# TAB 2 — EVOLUCIÓN NACIONAL (2022–2025)
# ---------------------------------------------------------
with tab2:
    st.header("Evolución Nacional de Denuncias por Cibercriminalidad (2022–2025)")
    st.caption("2022–2024 datos reales · 2025 predicción del modelo")

    # 1) TOTAL NACIONAL
    
    df_total_nac = df.groupby(["periodo", "Tipo_periodo"])["Total_Hechos"].sum().reset_index()
    st.plotly_chart(plot_evolucion(
        df_total_nac,
        "Evolución Nacional del Total de Denuncias (2022–2025)",
        "Total de denuncias",
        "#1f77b4", "#9467bd"
    ), use_container_width=True)

    # 2) FRAUDE INFORMÁTICO
    
    df_fraude = df[df["Grupo penal"] == "fraude_informatico"].groupby(["periodo", "Tipo_periodo"])["Total_Hechos"].sum().reset_index()
    st.plotly_chart(plot_evolucion(
        df_fraude,
        "Evolución Nacional del Fraude Informático (2022–2025)",
        "Denuncias por fraude informático",
        "orange", "red"
    ), use_container_width=True)

    # 3) OTROS CIBERDELITOS
    
    df_otros = df[df["Grupo penal"] != "fraude_informatico"].groupby(["periodo", "Tipo_periodo"])["Total_Hechos"].sum().reset_index()
    st.plotly_chart(plot_evolucion(
        df_otros,
        "Evolución Nacional de Otros Ciberdelitos (2022–2025)",
        "Otros ciberdelitos (total)",
        "green", "darkgreen"
    ), use_container_width=True)


# ---------------------------------------------------------
# TAB 3 — ANÁLISIS DE FRAUDE INFORMÁTICO (2025)
# ---------------------------------------------------------

with tab3:
    st.header("Análisis de Denuncias por Fraude Informático")
    st.caption("2022–2024 datos reales · 2025 predicción del modelo")

    # --- DATOS ---
    df_fraude = df[df["Grupo penal"] == "fraude_informatico"].copy()
    df_2025_pred = df_fraude[(df_fraude["periodo"] == "2025") & (df_fraude["Tipo_periodo"] == "Predicción")].copy()
    años = sorted(df_fraude["periodo"].unique())

# 1. Mapa: Distribución Peso Fraude %
    st.subheader("Distribución Peso Fraude Informático %")
    st.caption("¿Cuánto condiciona el fraude informático la estructura delictiva por Cibercrimen?")
    
    # Ajuste: Forzamos la carga inicial en 2025
    año_inicio_mapa = "2025"
    df_map_init = df_fraude[df_fraude["periodo"] == año_inicio_mapa].sort_values("codigo_ine")
    
    fig_map = px.choropleth(
        df_map_init,
        geojson=geojson, locations="codigo_ine", featureidkey="properties.cod_prov",
        color="Peso_Fraude", hover_name="Provincias",
        hover_data={"codigo_ine": False, "Peso_Fraude": ":.2f", "Tasa_Criminalidad": ":.2f"},
        color_continuous_scale="Plasma"
    )

    # Configuración de botones
    botones_map = [dict(label=str(a), method="update", 
                        args=[{"z": [df_fraude[df_fraude["periodo"]==a].sort_values("codigo_ine")["Peso_Fraude"].values]}]) 
                   for a in años]
    
    fig_map.update_layout(
        # QUITAMOS el title de aquí para que no desplace el menú
        updatemenus=[dict(
            type="dropdown", 
            buttons=botones_map, 
            x=0,          # Alineado totalmente a la izquierda
            y=1.1,        # Posición vertical ajustada
            xanchor="left", 
            yanchor="top"
        )],
        margin=dict(t=50, b=10, l=10, r=10), # Margen superior reducido
        height=600
    )
    fig_map.update_geos(fitbounds="locations", visible=False)
    st.plotly_chart(fig_map, use_container_width=True)

    st.markdown(
    "<p style='font-size:0.9rem; color:gray;'>"
    "<b>Interpretación:</b> Como se aprecia en el mapa, el fraude informático concentra la "
    "mayoría de las denuncias por cibercrimen en prácticamente todas las provincias, "
    "superando habitualmente el 85–90% del total."
    "</p>",
    unsafe_allow_html=True
)

    # 2. Fila 2: Tablas Top 5 y Evolución
    col_izq, col_der = st.columns([1, 1])

    with col_izq:
        # Tabla Tasa (Formateo de Tasa_Criminalidad a 2 decimales)
        st.subheader("Top 5 Provincias Mayor Tasa de Criminalidad por Fraude Informático 2025")
        top_5_tasa = df_2025_pred.sort_values("Tasa_Criminalidad", ascending=False).head(5)
        st.table(top_5_tasa[["Provincias", "Tasa_Criminalidad"]]
                 .rename(columns={"Tasa_Criminalidad": "Tasa de Criminalidad (x 1.000 hab)"})
                 .style.format({"Tasa de Criminalidad (x 1.000 hab)": "{:.2f}"}))
        st.markdown(
    "<p style='font-size:0.9rem; color:gray;'>"
    "<b>Interpretación:</b> La tasa de Criminalidad indica cuántas denuncias de fraude informático se registran "
    "por cada 1.000 habitantes. Un valor de 11 significa que, de media, se producen 11 denuncias "
    "por cada 1.000 residentes en esa provincia, independientemente del tamaño total de su población."
    "</p>",
    unsafe_allow_html=True
)
        # Tabla Incremento (Formateo de VAR_pct a 2 decimales)
        st.subheader("Top 5 Provincias: Mayor Incremento Fraude Informático (2025 vs 2024)")
        top_5_var = df_2025_pred.sort_values("VAR_pct", ascending=False).head(5)
        st.table(top_5_var[["Provincias", "VAR_pct"]]
                 .rename(columns={"VAR_pct": "Incremento VAR_pct(%)"})
                 .style.format({"Incremento VAR_pct(%)": "{:.2f}"}))
        st.markdown(
    "<p style='font-size:0.9rem; color:gray;'>"
    "<b>Interpretación:</b> El indicador VAR_pct muestra el crecimiento relativo del fraude "
    "informático respecto al año anterior. Un valor del 20% significa que en 2025 se registraron "
    "un 20% más denuncias que en 2024 en esa provincia, independientemente del volumen total o "
    "de su población."
    "</p>",
    unsafe_allow_html=True
)
    with col_der:
        st.subheader("Evolución Provincial de Denuncias 2025")
        prov_sel = st.selectbox("Seleccione provincia:", sorted(df_fraude["Provincias"].unique()), key="ts_prov")
        df_ts = df_fraude[df_fraude["Provincias"] == prov_sel].sort_values("periodo")
        
        ultimo_dato = df_ts.iloc[-1]
        m1, m2, m3 = st.columns(3)
        m1.metric("Total Hechos (2025)", f"{int(ultimo_dato['Total_Hechos']):,}".replace(",", "."))
        m2.metric("Peso Fraude", f"{ultimo_dato['Peso_Fraude']:.2f}%")
        m3.metric("Tasa Criminalidad", f"{ultimo_dato['Tasa_Criminalidad']:.2f}%")
        st.markdown(
    "<p style='font-size:0.9rem; color:gray;'>"
    "<b>Lectura:</b> El gráfico muestra la evolución anual del total de denuncias por fraude "
    "informático en la provincia seleccionada, incluyendo datos reales (2022–2024) y la "
    "predicción estimada para 2025."
    "</p>",
    unsafe_allow_html=True
)
       
        st.plotly_chart(plot_evolucion(df_ts, "", "Denuncias", "orange", "red"), use_container_width=True)

# 3. Fila 3: Mapa Variación Interanual (VAR%) - Comparativa
    st.subheader("Mapa de Variación Interanual (VAR%)")
    
    # Ajuste 1: Definimos los años válidos (2023, 2024, 2025) y los ordenamos de mayor a menor
    años_var = sorted([a for a in años if int(a) >= 2023], reverse=True)
    
    # Ajuste 2: Mapa inicial forzado a 2025
    año_inicial = "2025"
    df_var_plot = df_fraude[df_fraude["periodo"] == año_inicial].sort_values("codigo_ine")
    
    fig_var = px.choropleth(
        df_var_plot, 
        geojson=geojson, locations="codigo_ine", featureidkey="properties.cod_prov",
        color="VAR_pct", color_continuous_scale="RdYlGn", hover_name="Provincias",
        range_color=[df_fraude["VAR_pct"].min(), df_fraude["VAR_pct"].max()]
    )
    
    # Ajuste 3: Botones recorriendo la lista ya ordenada (2025, 2024, 2023)
    botones_var = [dict(label=str(a), method="update", 
                        args=[{"z": [df_fraude[df_fraude["periodo"]==a].sort_values("codigo_ine")["VAR_pct"].values]},
                              {"title": f"Mapa de Variación Interanual ({a})"}]) for a in años_var]

    fig_var.update_layout(
        updatemenus=[dict(type="dropdown", buttons=botones_var, x=0, y=1.15)],
        margin=dict(t=80, b=10, l=10, r=10), height=600
    )
    fig_var.update_geos(fitbounds="locations", visible=False)
    
    st.plotly_chart(fig_var, use_container_width=True)
    st.markdown(
    "<p style='font-size:0.9rem; color:gray;'>"
    "<b>Lectura:</b> La variación interanual (VAR%) muestra cómo cambia el fraude informático "
    "respecto al año anterior. Tras el fuerte crecimiento observado entre 2022 y 2023, el patrón "
    "reciente es más estable: en la mayoría de provincias el incremento es moderado y en algunas "
    "zonas incluso se aprecia cierto estancamiento."
    "</p>",
    unsafe_allow_html=True
)


#--------------------------------------------------------
#--------------------------------------------------------
# TAB4 OTROS CIBERDELITOS 
#--------------------------------------------------------
with tab4:
    st.header("Análisis de Denuncias Otros Ciberdelitos")

    # 1. FILTRADO: Mantenemos todas las columnas del CSV original
    # Excluimos fraude y nos quedamos con el resto de tipologías
    df_otros = df[df["Grupo penal"] != "fraude_informatico"].copy()

    # IMPORTANTE: Para la visualización de "Otros", sumamos los hechos por Provincia/Año
    # Pero para no perder las columnas, hacemos un merge o un cálculo inteligente.
    # La forma más segura para tu función plot_evolucion es esta:

    # Agrupamos solo los hechos para el cálculo, pero mantenemos las columnas base
    df_agrupado = df_otros.groupby(["Provincias", "periodo", "Tipo_periodo", "codigo_ine", "Poblacion_Provincial"])["Total_Hechos"].sum().reset_index()

    # Recalculamos la tasa para el total de "Otros"
    df_agrupado["Tasa_Criminalidad"] = (df_agrupado["Total_Hechos"] / df_agrupado["Poblacion_Provincial"]) * 1000

# ---------------------------------------------------------------------
# BLOQUE ÚNICO Y ESTABLE: Análisis Detallado (Variables y Cálculos)
# ---------------------------------------------------------------------

    # 1. CÁLCULO DE DATOS (Centralizado para evitar errores de nombre)
    df_detallado = df_otros.groupby(["Provincias", "Grupo penal", "periodo", "Poblacion_Provincial"])["Total_Hechos"].sum().reset_index()
    df_detallado["Tasa"] = (df_detallado["Total_Hechos"] / df_detallado["Poblacion_Provincial"]) * 1000
    df_pivot_det = df_detallado.pivot_table(index=["Provincias", "Grupo penal"], columns="periodo", values="Tasa", fill_value=0)

# Forzamos columnas para evitar errores de dataset incompleto
    if "2024" not in df_pivot_det.columns: df_pivot_det["2024"] = 0
    if "2025" not in df_pivot_det.columns: df_pivot_det["2025"] = 0
    df_pivot_det["Δ Tasa"] = df_pivot_det["2025"] - df_pivot_det["2024"]

    # 2. MAPA: Distribución Tasa Criminalidad
    st.subheader("Distribución Tasa de Criminalidad – Total Otros Ciberdelitos (x 1.000 hab) 2022 - 2025")
    st.markdown(
    "<p style='font-size:0.9rem; color:gray;'>"
    "<b>Lectura:</b> Este mapa representa la tasa total de denuncias por los siete ciberdelitos "
    "distintos del fraude informático. La tasa indica cuántas denuncias se registran por cada "
    "1.000 habitantes en cada provincia, permitiendo comparar territorios con poblaciones muy "
    "diferentes."
    "</p>",
    unsafe_allow_html=True
)

    años = sorted(df_agrupado["periodo"].unique())

    # Mapa inicial (2025)
    fig_map = px.choropleth(
        df_agrupado[df_agrupado["periodo"] == "2025"].sort_values("codigo_ine"),
        geojson=geojson, locations="codigo_ine", featureidkey="properties.cod_prov",
        color="Tasa_Criminalidad", hover_name="Provincias",
        hover_data={"codigo_ine": False, "Tasa_Criminalidad": ":.2f"},
        color_continuous_scale="Viridis"
    )

    botones_map = [dict(label=str(a), method="update",
                        args=[{"z": [df_agrupado[df_agrupado["periodo"]==a].sort_values("codigo_ine")["Tasa_Criminalidad"].values]}])
                   for a in años]

    fig_map.update_layout(
        updatemenus=[dict(type="dropdown", buttons=botones_map, x=0, y=1.1, xanchor="left", yanchor="top")],
        margin=dict(t=50, b=10, l=10, r=10), height=600
    )
    fig_map.update_geos(fitbounds="locations", visible=False)
    st.plotly_chart(fig_map, use_container_width=True)
    st.markdown(
    "<p style='font-size:0.85rem; color:gray;'>"
    "<i>El total de 'Otros ciberdelitos' agrupa siete tipologías: amenazas y coacciones, "
    "falsificación informática, acceso e interceptación ilícita, interferencia en datos y sistemas, "
    "delitos sexuales digitales, delitos contra el honor y delitos contra la propiedad "
    "industrial/intelectual.</i>"
    "</p>",
    unsafe_allow_html=True
)


# 3. MAPA DE CRECIMIENTO (TOTAL Y DESAGREGADO)
    st.subheader("Mapa de Calor: Evolución del Crecimiento (2025 vs 2024)")
    st.markdown(
    "<p style='font-size:0.85rem; color:gray;'>"
    "<i>Las tipologías incluidas en 'Otros ciberdelitos' presentan una incidencia muy baja en "
    "comparación con el fraude informático. Por ello, las tasas y sus variaciones suelen ser "
    "pequeñas incluso cuando se producen cambios reales en el número de denuncias.</i>"
    "</p>",
    unsafe_allow_html=True
)

    
    # 1. Definimos las opciones: Primero el Total, luego la lista de delitos
    lista_delitos = [
        "TOTAL Otros Ciberdelitos",
        "interferencia_en_los_datos_y_en_el_sistema",
        "amenazas_y_coacciones",
        "delitos_sexuales",
        "falsificacion_informatica",
        "contra_el_honor",
        "acceso_e_interceptacion_ilicita",
        "contra_la_propiedad_industrial_intelectual"
    ]
    
    delito_seleccionado = st.selectbox("Seleccione qué desea visualizar:", lista_delitos)
    
    # 2. Lógica de filtrado
    if delito_seleccionado == "TOTAL Otros Ciberdelitos":
        # Usamos df_otros completo
        df_filtro = df_otros.copy()
    else:
        # Filtramos por el delito seleccionado
        df_filtro = df_otros[df_otros["Grupo penal"] == delito_seleccionado].copy()
    
    # 3. Cálculo del Delta para la selección actual
    df_det = df_filtro.groupby(["Provincias", "periodo", "Poblacion_Provincial"])["Total_Hechos"].sum().reset_index()
    df_det["Tasa"] = (df_det["Total_Hechos"] / df_det["Poblacion_Provincial"]) * 1000
    df_pivot = df_det.pivot_table(index="Provincias", columns="periodo", values="Tasa", fill_value=0)
    
    # Aseguramos columnas 2024/2025
    if "2024" not in df_pivot.columns: df_pivot["2024"] = 0
    if "2025" not in df_pivot.columns: df_pivot["2025"] = 0
    
    df_pivot["Δ Tasa"] = df_pivot["2025"] - df_pivot["2024"]
    df_delta_map = df_pivot.reset_index().merge(df_agrupado[["Provincias", "codigo_ine"]].drop_duplicates(), on="Provincias")

    # 4. Mapa
    fig_delta = px.choropleth(
        df_delta_map, geojson=geojson, locations="codigo_ine", featureidkey="properties.cod_prov",
        color="Δ Tasa", hover_name="Provincias", color_continuous_scale="RdBu_r"
    )
    fig_delta.update_geos(fitbounds="locations", visible=False)
    fig_delta.update_layout(height=600)
    st.plotly_chart(fig_delta, use_container_width=True)
    st.markdown(
    "<p style='font-size:0.85rem; color:gray;'>"
    "Nota:<i>En varias provincias algunas tipologías presentan valores nulos (0 denuncias en 2024 y "
    "2025). En estos casos, el Δ Tasa aparece como 0, lo que no indica estabilidad sino ausencia "
    "de denuncias registradas para esa tipología.</i>"
    "</p>",
    unsafe_allow_html=True
)


# ---------------------------------------------------------------------
    # 2. ESTRUCTURA VISUAL (Columnas y Contenido)
    # ---------------------------------------------------------------------
    col_izq, col_der = st.columns([1, 1])

    with col_izq:
        # --- INCIDENCIA ---
        st.subheader("Top 5 Provincias: Incidencia (2025)")
        top_tasa = df_agrupado[df_agrupado["periodo"] == "2025"].sort_values("Tasa_Criminalidad", ascending=False).head(5)
        tabla_display = top_tasa[["Provincias", "Total_Hechos", "Tasa_Criminalidad"]].rename(columns={"Total_Hechos": "Nº Denuncias", "Tasa_Criminalidad": "Tasa (por 1.000 hab.)"})
        st.dataframe(tabla_display.style.format({"Nº Denuncias": "{:.0f}", "Tasa (por 1.000 hab.)": "{:.3f}"}), use_container_width=True)
        st.markdown("**Interpretación:** La Tasa mide la intensidad por cada 1.000 habitantes. **Nota:** Registra denuncias, no víctimas individuales.")

        st.markdown("---") 

        # --- ALERTAS ---
        st.subheader("Alertas: Mayor Incremento (2024-2025)")
        top_alertas = df_pivot_det.sort_values("Δ Tasa", ascending=False).head(5).reset_index()
        st.dataframe(top_alertas[["Provincias", "Grupo penal", "Δ Tasa"]].style.format({"Δ Tasa": "{:.3f}"}), use_container_width=True)
        st.markdown("**¿Qué mide?** Aumento neto en la intensidad delictiva (puntos de tasa) entre 2024 y 2025.")

    with col_der:
        # --- EVOLUCIÓN ---
        st.subheader("Evolución Provincial")
        prov_sel = st.selectbox("Seleccione provincia:", sorted(df_agrupado["Provincias"].unique()), key="ts_prov_final")
        df_prov = df_agrupado[df_agrupado["Provincias"] == prov_sel].sort_values("periodo")
        
        if not df_prov.empty:
            ult = df_prov.iloc[-1]
            m1, m2 = st.columns(2)
            m1.metric("Hechos 2025", f"{int(ult['Total_Hechos']):,}".replace(",", "."))
            m2.metric("Tasa 2025", f"{ult['Tasa_Criminalidad']:.3f}")
            st.plotly_chart(plot_evolucion(df_prov, "", "Denuncias", "teal", "green"), use_container_width=True)
            
            # Desglose Tipologías
            st.write(f"**Tipologías en {prov_sel.capitalize()} (2025)**")
            df_det = df_otros[(df_otros["Provincias"] == prov_sel) & (df_otros["periodo"] == "2025")].copy()
            df_det["Peso %"] = (df_det["Total_Hechos"] / df_det["Total_Hechos"].sum()) * 100
            st.table(df_det[["Grupo penal", "Total_Hechos", "Peso %"]].sort_values("Total_Hechos", ascending=False).rename(columns={"Grupo penal": "Tipología", "Total_Hechos": "Denuncias"}).style.format({"Denuncias": "{:.0f}", "Peso %": "{:.1f}%"}))

    # ---------------------------------------------------------------------
    # 3. FOCO ESTRATÉGICO (Ancho completo)
    # ---------------------------------------------------------------------
    st.markdown("---")
    st.subheader("Foco Estratégico: Mayor crecimiento por Delito (2025 vs 2024)")
    st.markdown(
    "<p style='font-size:0.85rem; color:gray;'>"
    "Nota:<i>Para cada tipología se muestra la provincia donde la tasa de denuncias experimenta el "
    "mayor crecimiento entre 2024 y 2025 (Δ Tasa, puntos por 1.000 habitantes).</i>"
    "</p>",
    unsafe_allow_html=True
)

    resumen_alertas = []
    for delito in df_pivot_det.reset_index()["Grupo penal"].unique():
        subset = df_pivot_det.reset_index()
        lider = subset[subset["Grupo penal"] == delito].loc[subset[subset["Grupo penal"] == delito]["Δ Tasa"].idxmax()]
        resumen_alertas.append({"Delito": delito, "Provincia": lider["Provincias"].capitalize(), "Δ Tasa": lider["Δ Tasa"]})

    cols = st.columns(len(resumen_alertas)) 
    for i, row in enumerate(resumen_alertas):
        with cols[i]:
            st.metric(label=row["Delito"].replace("_", " ").title(), value=row["Provincia"], delta=f"{row['Δ Tasa']:.3f}")